### ISSUE TITLE
Can't login with GitHub to let a comment

### ISSUE THREAD

**Issue by Xwilarg** [EvanMu96/EvanMu96.github.io#1]
Hey,

Just letting a small issue to say that we can't connect using GitHub on your website, it instead redirect to the main page with the following URL:

https://blog.senevan.com/?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdocs.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23redirect-uri-mismatch

**Comment by EvanMu96** [comment]
Hi Xwilarg,
Thanks for reporting. I forgot to update Github Application Auth URL after changing domain name from `*.github.io` to my own one. It should be fixed now.
